blank_issues_enabled: false
contact_links:
  - name: Questions and ideas
    url: https://github.com/petty-foss-dev/MemoryManager/discussions
    about: Ask a question or develop an idea with the community before opening an issue.
  - name: Discord community
    url: https://discord.gg/Hw4nmXRehb
    about: Talk with the community.
